version: 2

project_name: opensoho

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: .
    binary: 
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

kos:
  -
    id: opensoho

    # Build ID that should be used to import the build settings.
    build: build_noncgo

    main: .

    working_dir: .

    base_image: alpine

    repositories:
      - ghcr.io/opensoho
    user: "0:0"

    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"

    creation_time: "{{.CommitTimestamp}}"

    ko_data_creation_time: "{{.CommitTimestamp}}"

    sbom: none
    base_import_paths: true
    bare: true
