# Use Alpine for a minimal image
FROM alpine:latest

# Install dependencies
RUN apk add --no-cache curl unzip tcpdump

# Download PocketBase
RUN curl -fsSL https://github.com/pocketbase/pocketbase/releases/download/v0.26.5/pocketbase_0.26.5_linux_amd64.zip -o pocketbase.zip \
    && unzip pocketbase.zip \
    && rm pocketbase.zip

# Expose the PocketBase default port
EXPOSE 8090

# Run PocketBase
CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090"]
