{{- if not .Values.sharedSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensoho.fullname" . }}
  labels:
    {{- include "opensoho.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "opensoho.sharedSecretKey" . }}: {{ required "sharedSecret.value or sharedSecret.existingSecret is required" .Values.sharedSecret.value | quote }}
{{- end }}
